### ISSUE TITLE
  File "/config/custom_components/ecodevices/sensor.py", line 420, in native_value     raise EcoDevicesIncorrectValueError("Total value not greater than 0.") custom_components.ecodevices.sensor.EcoDevicesIncorrectValueError: Total value not greater than 0.

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#37]
Bonjour,

Je rencontre une erreur avec le plugin ecodevices dans HA. 
Savez-vous comment corriger le problème ?

```
logger: homeassistant
Source: custom_components/ecodevices/sensor.py:420
Integration: GCE Eco-Devices (documentation, issues)
First occurred: 09:51:03 (1 occurrences)
Last logged: 09:51:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecodevices/sensor.py", line 420, in native_value
    raise EcoDevicesIncorrectValueError("Total value not greater than 0.")
custom_components.ecodevices.sensor.EcoDevicesIncorrectValueError: Total value not greater than 0.
```

Cordialement
Ludovic

**Comment by lboue** [comment]
![image](https://user-images.githubusercontent.com/938089/229826113-8ffa64ae-4fe0-40d7-b876-e9843326a989.png)

**Comment by Aohzan** [comment]
Bonjour,
Il s'agit d'une sécurité quand l'Eco Devices renvoie une valeur de 0 incorrecte et qui est ignorée pour éviter de casser les statistiques, je vais voir dans une prochaine version pour juste remonter en warning ou info et non plus en erreur

**Comment by Aohzan** [comment]
Réglé en https://github.com/Aohzan/ecodevices/releases/tag/4.5.0
