### ISSUE TITLE
Erreur à l'ajout d'un Eco-Device

### ISSUE THREAD

**Issue by SubZ69** [Aohzan/ecodevices#39]
Salut, j'essaye de rajouter mon eco-device mais malheureusement j'ai ce message d'erreur : 
```
2023-08-05 21:00:36.458 DEBUG (MainThread) [custom_components.ecodevices] Finished fetching ecodevices data in 0.269 seconds (success: True)
2023-08-05 21:00:36.460 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Eco-Devices 192.168.1.50:80 for ecodevices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecodevices/__init__.py", line 93, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 511, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 165, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'configuration_url': 'http://192.168.1.50:80', 'connections': {('mac', '00:1E:C0:F3:B8:22')}, 'default_name': 'Eco-Devices 192.168.1.50:80', 'identifiers': {('ecodevices', '00:1E:C0:F3:B8:22')}, 'manufacturer': 'GCE', 'model': 'Eco-Devices', 'sw_version': '1.05.24'} for 'ecodevices' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

**Comment by noelbrice** [comment]
Bonjour, 
J'ai la même erreur, mon ecodevice ne fonctionne plus depuis mise à jour home assistant 2023.8.1.

**Comment by Aohzan** [comment]
Bonjour, il faut upgrade en https://github.com/Aohzan/ecodevices/releases/tag/4.6.1

**Comment by SubZ69** [comment]
Fonctionne parfaitement, merci pour ta réactivité :+1:

**Comment by noelbrice** [comment]
Merci parfait
