### ISSUE TITLE
Les infos de l'Eco Device ne remontent plus

### ISSUE THREAD

**Issue by LudoBoyer** [Aohzan/ecodevices#54]
Depuis la mise à jour de HA en 2024.12.1 les infos ne remontent plus.
L'interface sur PC est bien fonctionnelle.
![Image2](https://github.com/user-attachments/assets/1797c52e-b105-4120-8703-70384040af24)

**Comment by Aohzan** [comment]
Les logs en debug :pray:

**Comment by LudoBoyer** [comment]
![HA](https://github.com/user-attachments/assets/cb36eede-871f-4a99-9829-6486295a9360)

**Comment by Aohzan** [comment]
c'est juste un warning ça, il me faut les logs debug avec un reload de l'intégration

**Comment by LudoBoyer** [comment]
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.ecodevices
Source: helpers/update_coordinator.py:379
intégration: GCE Eco-Devices (documentation, problèmes)
S'est produit pour la première fois: 12:00:11 (9 occurrences)
Dernier enregistrement: 12:02:45

Unexpected error fetching ecodevices data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecodevices/__init__.py", line 108, in async_update_data
    return await controller.global_get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyecodevices/__init__.py", line 107, in global_get
    result.update(await self._request(self._api_teleinfo_1_url))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyecodevices/__init__.py", line 79, in _request
    xml_content = xmltodict.parse(contents)
  File "/usr/local/lib/python3.13/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 24, column 11

**Comment by Aohzan** [comment]
il semble que c'est l'ecodevices qui ne renvoie pas des infos correctes, voir https://github.com/Aohzan/ecodevices/issues/35#issuecomment-1621216562

**Comment by LudoBoyer** [comment]
Bon et bien malgré que l’interface de l’ecodevice soit fonctionnelle un reboot aura été nécessaire.
Tout est rentré dans l’ordre.
Désolé pour le dérangement et merci.
